-- ============================================================
-- 견적요청(Quote Request) 테이블 DDL
-- Air/Sea 통합 테이블 (BIZ_TYPE 컬럼으로 구분)
-- ============================================================

-- 1. 메인 헤더 테이블
CREATE TABLE IF NOT EXISTS QUO_QUOTE_REQUEST (
  REQUEST_ID      INT AUTO_INCREMENT PRIMARY KEY,
  REQUEST_NO      VARCHAR(20) NOT NULL COMMENT '견적번호 (QR-YYYY-NNNN)',
  REQUEST_DATE    DATE NOT NULL COMMENT '등록일자',
  BIZ_TYPE        VARCHAR(10) DEFAULT 'SEA' COMMENT '업무구분 (SEA/AIR)',
  IO_TYPE         VARCHAR(10) DEFAULT 'EXPORT' COMMENT '수출입구분 (EXPORT/IMPORT)',
  CUSTOMER_ID     INT NULL COMMENT '거래처ID',
  CUSTOMER_NM     VARCHAR(200) NULL COMMENT '거래처명',
  INPUT_EMPLOYEE  VARCHAR(100) NULL COMMENT '입력사원',
  ORIGIN_CD       VARCHAR(10) NULL COMMENT '출발지 코드',
  ORIGIN_NM       VARCHAR(100) NULL COMMENT '출발지명',
  DEST_CD         VARCHAR(10) NULL COMMENT '도착지 코드',
  DEST_NM         VARCHAR(100) NULL COMMENT '도착지명',
  INCOTERMS       VARCHAR(10) DEFAULT 'CIF' COMMENT '무역조건',
  SHIPPING_DATE   DATE NULL COMMENT '출고예정일',
  COMMODITY       VARCHAR(200) NULL COMMENT '품목/화물설명',
  CARGO_TYPE      VARCHAR(20) DEFAULT 'GENERAL' COMMENT '화물구분 (GENERAL/SPECIAL/DG/REEFER)',
  WEIGHT_KG       DECIMAL(18,3) NULL COMMENT '중량(kg)',
  VOLUME_CBM      DECIMAL(18,3) NULL COMMENT '용적(CBM)',
  QUANTITY        INT NULL COMMENT '수량',
  TOTAL_AMOUNT    DECIMAL(18,2) DEFAULT 0 COMMENT '총 견적금액',
  CURRENCY_CD     VARCHAR(3) DEFAULT 'USD' COMMENT '통화코드',
  STATUS          VARCHAR(20) DEFAULT '01' COMMENT '견적상태 (01미요청/02요청/03확인/04승인/05거절)',
  REMARK          TEXT NULL COMMENT '비고',
  CREATED_BY      VARCHAR(50) DEFAULT 'admin',
  CREATED_DTM     DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY      VARCHAR(50) NULL,
  UPDATED_DTM     DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  DEL_YN          CHAR(1) DEFAULT 'N' COMMENT '소프트 삭제',
  INDEX idx_request_no (REQUEST_NO),
  INDEX idx_biz_type (BIZ_TYPE),
  INDEX idx_status (STATUS),
  INDEX idx_created_dtm (CREATED_DTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='견적요청 메인';

-- 2. 운임정보 서브테이블 (Air/Sea 슈퍼셋)
CREATE TABLE IF NOT EXISTS QUO_QUOTE_REQUEST_RATE (
  RATE_ID         INT AUTO_INCREMENT PRIMARY KEY,
  REQUEST_ID      INT NOT NULL COMMENT '견적요청ID (FK)',
  RATE_SEQ        INT DEFAULT 1 COMMENT '순번',
  RATE_TYPE       VARCHAR(50) NULL COMMENT '운임유형',
  RATE_CD         VARCHAR(50) NULL COMMENT '운임코드',
  CURRENCY_CD     VARCHAR(3) DEFAULT 'USD' COMMENT '통화단위',
  REMARK          VARCHAR(500) NULL COMMENT '비고',
  -- Air 전용 (PPT 슬라이드10)
  RATE_MIN        DECIMAL(18,2) NULL COMMENT 'Air: Rate Min',
  RATE_45L        DECIMAL(18,2) NULL COMMENT 'Air: -45L',
  RATE_45         DECIMAL(18,2) NULL COMMENT 'Air: +45',
  RATE_100        DECIMAL(18,2) NULL COMMENT 'Air: +100',
  RATE_300        DECIMAL(18,2) NULL COMMENT 'Air: +300',
  RATE_500        DECIMAL(18,2) NULL COMMENT 'Air: +500',
  RATE_1000       DECIMAL(18,2) NULL COMMENT 'Air: +1000',
  RATE_PER_KG     DECIMAL(18,2) NULL COMMENT 'Air: Rate Per KG',
  RATE_BL         DECIMAL(18,2) NULL COMMENT 'Air: Rate BL',
  -- Sea 전용 (PPT 슬라이드12)
  RATE_PER_MIN    DECIMAL(18,2) NULL COMMENT 'Sea: Rate Per Min',
  RATE_PER_BL     DECIMAL(18,2) NULL COMMENT 'Sea: Rate Per BL',
  RATE_PER_RTON   DECIMAL(18,2) NULL COMMENT 'Sea: Rate Per R.Ton',
  RATE_DRY_20     DECIMAL(18,2) NULL COMMENT 'Sea: Container DRY 20',
  RATE_DRY_40     DECIMAL(18,2) NULL COMMENT 'Sea: Container DRY 40',
  CNTR_TYPE_A_CD  VARCHAR(20) NULL COMMENT 'Sea: Type A Code',
  CNTR_TYPE_A_RATE DECIMAL(18,2) NULL COMMENT 'Sea: Type A Rate',
  CNTR_TYPE_B_CD  VARCHAR(20) NULL COMMENT 'Sea: Type B Code',
  CNTR_TYPE_B_RATE DECIMAL(18,2) NULL COMMENT 'Sea: Type B Rate',
  CNTR_TYPE_C_CD  VARCHAR(20) NULL COMMENT 'Sea: Type C Code',
  CNTR_TYPE_C_RATE DECIMAL(18,2) NULL COMMENT 'Sea: Type C Rate',
  RATE_BULK       DECIMAL(18,2) NULL COMMENT 'Sea: Bulk Rate',
  DEL_YN          CHAR(1) DEFAULT 'N',
  INDEX idx_request_id (REQUEST_ID),
  CONSTRAINT fk_rate_request FOREIGN KEY (REQUEST_ID) REFERENCES QUO_QUOTE_REQUEST(REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='견적요청 운임정보';

-- 3. 운송요율 서브테이블 (Air/Sea 슈퍼셋)
CREATE TABLE IF NOT EXISTS QUO_QUOTE_REQUEST_TRANSPORT (
  TRANSPORT_ID    INT AUTO_INCREMENT PRIMARY KEY,
  REQUEST_ID      INT NOT NULL COMMENT '견적요청ID (FK)',
  TRANSPORT_SEQ   INT DEFAULT 1 COMMENT '순번',
  RATE_CD         VARCHAR(50) NULL COMMENT '운임코드',
  ORIGIN_CD       VARCHAR(10) NULL COMMENT '출발지 코드',
  ORIGIN_NM       VARCHAR(100) NULL COMMENT '출발지명',
  DEST_CD         VARCHAR(10) NULL COMMENT '도착지 코드',
  DEST_NM         VARCHAR(100) NULL COMMENT '도착지명',
  ETC_DESC        VARCHAR(500) NULL COMMENT 'E.T.C 설명',
  CONTACT_NM      VARCHAR(100) NULL COMMENT '담당자',
  CONTACT_TEL     VARCHAR(50) NULL COMMENT '전화',
  CONTACT_FAX     VARCHAR(50) NULL COMMENT '팩스',
  CONTACT_EMAIL   VARCHAR(200) NULL COMMENT '이메일',
  -- Air 전용 (PPT 슬라이드10-11)
  TRANSPORT_TYPE  VARCHAR(50) NULL COMMENT 'Air: 운송구분',
  VEHICLE_TYPE    VARCHAR(50) NULL COMMENT 'Air: 차량유형',
  AMOUNT          DECIMAL(18,2) NULL COMMENT 'Air: 금액',
  -- Sea 전용 (PPT 슬라이드12-13)
  RATE_LCL        DECIMAL(18,2) NULL COMMENT 'Sea: LCL Rate',
  RATE_20FT       DECIMAL(18,2) NULL COMMENT 'Sea: 20FT Rate',
  RATE_40FT       DECIMAL(18,2) NULL COMMENT 'Sea: 40FT Rate',
  DEL_YN          CHAR(1) DEFAULT 'N',
  INDEX idx_request_id (REQUEST_ID),
  CONSTRAINT fk_transport_request FOREIGN KEY (REQUEST_ID) REFERENCES QUO_QUOTE_REQUEST(REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='견적요청 운송요율';
